gText_WantToSurfWithPokemon:
    .string "The water is dyed a deep blue…\n"
    .string "Want {STR_VAR_1} to help you SURF?$"

gText_MonHelpedSurf:
    .string "{STR_VAR_1} helped you travel across\n"
    .string "the water!$"

gText_WantToSurfWithItem:
    .string "The water is a deep blue...\n"
    .string "Use the {STR_VAR_2}?$"

gText_PlayerUsedSurfItem:
    .string "You used the {STR_VAR_2} to travel across\n"
    .string "the water!$"
    
gText_CantSurf:
	.string "The water is dyed a deep blue.\n"

@ will likely delete the below
gText_WantToUseSurf::
	.string "The water is dyed a deep blue…\n"
	.string "Would you like to SURF?$"

gText_PlayerUsedSurf::
	.string "{STR_VAR_1} used SURF!$"

Text_CurrentTooFast::
	.string "The current is much too fast!\n"
	.string "SURF can't be used here…$"
